language: ruby
rvm:
  - "1.8.7"
before_install:
  - gem update --system 1.3.7
  - gem --version
before_script:
  - cp config/database.yml.example config/database.yml
  - cp spec/spec.opts.example spec/spec.opts
  - gem install mysql -i vendor/ --no-ri --no-rdoc
  - mysql -u root -e "CREATE DATABASE dashboard_test"
  - mysql -u root -e "GRANT ALL PRIVILEGES ON dashboard_test.* TO 'dashboard'@'localhost'"
  - rake db:migrate
script:
  - rake spec
